services:
  db:
    ports:
      - "127.0.0.1:${DB_HOST_PORT:-5432}:5432"

  nextjs_migrate:
    build:
      context: ./apps/nextjs_app
    image: wordrace-nextjs:development

  nextjs_app:
    build:
      context: ./apps/nextjs_app
    image: wordrace-nextjs:development
    ports:
      - "3000:3000"

  search_agent_migrate:
    build:
      context: ./apps/search_agent
    image: wordrace-search-agent:development

  search_agent_app:
    build:
      context: ./apps/search_agent
    image: wordrace-search-agent:development
    ports:
      - "${SEARCH_AGENT_PORT:-8000}:${SEARCH_AGENT_PORT:-8000}"
