"""init

Revision ID: ad0f9b88eecb
Revises: 
Create Date: 2026-05-16 12:29:04.350390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'ad0f9b88eecb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Vector columns require the pgvector extension supplied by the database image.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embeddings',
    sa.Column('word', sa.TEXT(), nullable=False),
    sa.Column('graph_id', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.CheckConstraint("word !~ '\\s'", name='no_space_in_term'),
    sa.ForeignKeyConstraint(['word'], ['dictionary.words.word'], name='embeddings_word_fkey'),
    sa.PrimaryKeyConstraint('word'),
    schema='ml'
    )
    op.create_index('idx_embeddings_embedding', 'embeddings', ['embedding'], unique=False, schema='ml', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_graph_id', 'embeddings', ['graph_id'], unique=False, schema='ml')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_graph_id', table_name='embeddings', schema='ml')
    op.drop_index('idx_embeddings_embedding', table_name='embeddings', schema='ml', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('embeddings', schema='ml')
    # ### end Alembic commands ###
