// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { SearchCollideData, SearchCollideErrors, SearchCollideResponses, SearchRegularData, SearchRegularErrors, SearchRegularResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Search
 *
 * Return a regular route or HTTP 404 when no legal route is found.
 */
export const searchRegular = <ThrowOnError extends boolean = false>(options: Options<SearchRegularData, ThrowOnError>): RequestResult<SearchRegularResponses, SearchRegularErrors, ThrowOnError> => (options.client ?? client).post<SearchRegularResponses, SearchRegularErrors, ThrowOnError>({
    url: '/search',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Collide Search
 *
 * Return two meeting routes or HTTP 404 when no collision is found.
 */
export const searchCollide = <ThrowOnError extends boolean = false>(options: Options<SearchCollideData, ThrowOnError>): RequestResult<SearchCollideResponses, SearchCollideErrors, ThrowOnError> => (options.client ?? client).post<SearchCollideResponses, SearchCollideErrors, ThrowOnError>({
    url: '/collide-search',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
