// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * CollideSearchResult
 *
 * Two complete directed paths ending at the same meeting word.
 */
export type CollideSearchResult = {
    /**
     * Start Path
     */
    start_path: Array<string>;
    /**
     * Target Path
     */
    target_path: Array<string>;
};

/**
 * EdgeConstraints
 *
 * Define the dictionary edges available to one search.
 *
 * Attributes:
 * lemmatized: Whether traversals use lemma links instead of surface words.
 * available_lexical_fields: Lexical relations available to the search.
 * available_pos: Target part-of-speech buckets available to the search.
 */
export type EdgeConstraints = {
    /**
     * Lemmatized
     */
    lemmatized?: boolean;
    /**
     * Available Lexical Fields
     */
    available_lexical_fields?: Array<SelectableLexicalKey>;
    /**
     * Available Pos
     */
    available_pos?: Array<WinkPosTag>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * RegularSearchResult
 *
 * A complete directed path from the requested start to target word.
 */
export type RegularSearchResult = {
    /**
     * Start Path
     */
    start_path: Array<string>;
};

/**
 * SearchRequest
 *
 * Specify two endpoint words and the graph edges available between them.
 */
export type SearchRequest = {
    /**
     * Start
     */
    start: string;
    /**
     * Target
     */
    target: string;
    constraints: EdgeConstraints;
};

/**
 * SelectableLexicalKey
 */
export type SelectableLexicalKey = 'antonyms' | 'synonyms' | 'hypernyms' | 'hyponyms' | 'holonyms' | 'meronyms' | 'derived' | 'related' | 'coordinate_terms' | 'glosses' | 'examples' | 'categories';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WinkPosTag
 */
export type WinkPosTag = 'ADJ' | 'ADP' | 'ADV' | 'AUX' | 'CCONJ' | 'DET' | 'INTJ' | 'NOUN' | 'NUM' | 'PART' | 'PRON' | 'PROPN' | 'PUNCT' | 'SCONJ' | 'SYM' | 'VERB' | 'X' | 'SPACE';

export type SearchRegularData = {
    body: SearchRequest;
    path?: never;
    query?: never;
    url: '/search';
};

export type SearchRegularErrors = {
    /**
     * No legal regular route was found.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchRegularError = SearchRegularErrors[keyof SearchRegularErrors];

export type SearchRegularResponses = {
    /**
     * Successful Response
     */
    200: RegularSearchResult;
};

export type SearchRegularResponse = SearchRegularResponses[keyof SearchRegularResponses];

export type SearchCollideData = {
    body: SearchRequest;
    path?: never;
    query?: never;
    url: '/collide-search';
};

export type SearchCollideErrors = {
    /**
     * No legal collide route was found.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchCollideError = SearchCollideErrors[keyof SearchCollideErrors];

export type SearchCollideResponses = {
    /**
     * Successful Response
     */
    200: CollideSearchResult;
};

export type SearchCollideResponse = SearchCollideResponses[keyof SearchCollideResponses];
